title: "Boilerplate"
author: "Boiler Plate"
email: boiler@plate.com
keywords: "boilerplate"
description: "Simple boilerplate for quickly setting up Jekyll with gulp builds for github pages"
timezone: Europe/Berlin

baseurl: "/"
url: "your.weburl.com"

markdown: kramdown
highlighter: rouge

# Github Pages
gem: [
  'jekyll-paginate',
  'jekyll-redirect-from',
  'jekyll-sitemap',
  'jekyll-seo-tag'
]

# Files to exclude from jekyll build
exclude: [
  '_dev',
  'node_modules',
  'bower.json',
  'bower_components',
  'package.json',
  'gulpfile.babel.js',
  '.babelrc',
  'Gemfile',
  'Gemfile.lock',
  'TODOs.org'
]
